/**
 * Better Auth server-side instance.
 *
 * This is the single source of truth for authentication and tenancy.
 *
 * Plugins in play:
 *  - `magicLink`     — passwordless sign-in via Resend (console fallback in dev)
 *  - `organization`  — multi-tenant orgs with members, roles, invitations
 *  - `nextCookies`   — App Router cookie helpers (must be last)
 *
 * Schema is generated by `pnpm auth:generate` (Better Auth CLI) into
 * `lib/db/auth-schema.ts` and imported here.
 */

import { betterAuth } from 'better-auth'
import { drizzleAdapter } from 'better-auth/adapters/drizzle'
import { nextCookies } from 'better-auth/next-js'
import { magicLink, organization } from 'better-auth/plugins'
import { db, schema as dbSchema } from '@/lib/db/client'
import { sendMagicLinkEmail } from '@/lib/email/magic-link'
import { env, isProduction } from '@/lib/env'
import { logger } from '@/lib/logger'

export const auth = betterAuth({
  baseURL: env.BETTER_AUTH_URL,
  secret: env.BETTER_AUTH_SECRET,

  database: drizzleAdapter(db, {
    provider: 'pg',
    schema: dbSchema,
    transaction: true,
  }),

  emailAndPassword: { enabled: false },

  session: {
    expiresIn: 60 * 60 * 24 * 30,
    updateAge: 60 * 60 * 24,
    cookieCache: { enabled: true, maxAge: 60 * 5 },
  },

  advanced: {
    cookiePrefix: 'aig',
    useSecureCookies: isProduction,
  },

  plugins: [
    magicLink({
      expiresIn: 60 * 15,
      sendMagicLink: async ({ email, url, token }) => {
        try {
          await sendMagicLinkEmail({ to: email, url, token })
        } catch (error) {
          logger.error({ err: error, email }, 'magic-link delivery failed')
          throw error
        }
      },
    }),

    organization({
      allowUserToCreateOrganization: true,
      organizationLimit: 5,
      membershipLimit: 100,
      creatorRole: 'owner',
      sendInvitationEmail: async (data) => {
        logger.info(
          {
            email: data.email,
            organizationId: data.organization.id,
            role: data.role,
          },
          'organization invitation issued (email delivery wired in Sprint 4)',
        )
      },
    }),

    nextCookies(),
  ],
})

export type Auth = typeof auth
